### ISSUE TITLE
La pop-up donnant le code s'affiche tout le temps 

### ISSUE THREAD

**Issue by the-smaug** [the-smaug/site-blend-program-generator#65]
La pop up donnant le code pour récup le menu de conférences enregistré s'affiche a chaque fois.
Cas testé : 
- menu enregistré dans le local storage
- après saisie du code permettant de récupérer une conférence

**Comment by sofaws** [comment]
Ok je vais voir, on est d'accord qu'elle doit s'afficher seulement au moment ou il génére un nouveau planning ?

**Comment by the-smaug** [comment]
Yes

**Comment by sofaws** [comment]
C'est fix ça normalement

**Comment by the-smaug** [comment]
absolument
